name: shorebird_test_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+3

environment:
  sdk: '>=3.1.2 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  # shorebird_code_push: ^1.1.3


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  assets:
    - shorebird.yaml
  uses-material-design: true

